id           = "rael2pac/gpu-temp"
name         = "GPU Temperature"
version      = "1.0.0"
plugin_api   = 4
author       = "rael2pac"
license      = "MIT"
icon         = "thermometer"
description  = "Configura o System Monitor do Noctalia para exibir temperatura da CPU e GPU nas widgets oficiais sysmon + temp"
tags         = ["System", "Temperature", "Config"]

[[service]]
id    = "gpu-temp"
entry = "service.luau"
